### ISSUE TITLE
Box and wiring diagram

### ISSUE THREAD

**Issue by dansche** [tchapi/uselessBox#1]
Hi, I like that Box very much, I would like to build it as a present. Can you tell me more about the Box itself, it looks printed, do you have any STL's i can get, furthermore I would be very interested in a wiring diagram, there is no information on here and i haven't found anything in the description.

If it's not a printed box, i would like to draw something myself, therefore i would need exact dimensions.

Hopefully you can still see this as the entry is from 2013.

Thanks

Dansche

**Comment by tchapi** [comment]
Hi,

I have added some 3D files and board schematics. Not sure if this is the right version though, since this is quite an old project, but worth giving it a try
